### ISSUE TITLE
接口似乎有问题，返回数据会被截断 invalid character '{' after top-level value

### ISSUE THREAD

**Issue by tisfeng** [missuo/cohere2openai#2]
测试几次，发现 stream 总是会被截断，cohere 官方接口没有问题。

## cohere2openai 接口

<img width="1246" alt="image" src="https://github.com/missuo/cohere2openai/assets/25194972/23da84a9-f475-477d-be4a-50eecb8c87f5">

## cohere 官方接口
<img width="1243" alt="image" src="https://github.com/missuo/cohere2openai/assets/25194972/4ceb8311-da2f-4359-9b40-901db49d2afd">

**Comment by missuo** [comment]
我有遇到类似的问题，昨天一直在和官方确认，我不清楚是什么导致的。目前正在排查，请等待更新，谢谢。

**Comment by missuo** [comment]
Fixed. https://github.com/missuo/cohere2openai/commit/73d6a1c3c8c21ce94489502de0511a31f0d0c58c

**Comment by tisfeng** [comment]
我拉最新的镜像测试，似乎还是有问题  {"error":"invalid character '{' after top-level value"}

```bash
curl --location --request POST 'http://localhost:6600/v1/chat/completions' \
--header 'Authorization: Bearer ' \
--header 'Content-Type: application/json' \
--data-raw '{
    "model": "command-r",
    "messages": [
      {
        "role": "system",
        "content": "将下面文本翻译为中文"
      },
      {
        "role": "user",
        "content": "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal."
      }
    ],
    "stream": true
  }'
```

<img width="1245" alt="image" src="https://github.com/missuo/cohere2openai/assets/25194972/3f69b359-50d9-4b93-8174-61d2a8a455dd">

**Comment by tisfeng** [comment]
多测试几次，之前的问题也出现了 {"error":"invalid character '{' after top-level value"}

<img width="1244" alt="image" src="https://github.com/missuo/cohere2openai/assets/25194972/bb9cb422-ba2a-48db-bb76-42639d7b1567">

**Comment by missuo** [comment]
<img width="1392" alt="image" src="https://github.com/missuo/cohere2openai/assets/55200481/630fb9d4-ce4d-41ce-ad73-102113741ee7">

似乎无法复现。

**Comment by tisfeng** [comment]
奇怪，我用你的接口地址 https://c.uid.si/v1/chat/completions 是正常的，难道是我本地部署有问题？等会我重新部署一下。

**Comment by missuo** [comment]
> 奇怪，我用你的接口地址 https://c.uid.si/v1/chat/completions 是正常的，难道是我本地部署有问题？等会我重新部署一下。

可能不是最新版？

**Comment by tisfeng** [comment]
ok，删了重新部署，现在好了 🙂
